apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: demo-wordpress-mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        tier: mysql
    spec:
      serviceAccountName: sa-wordpress
      containers:
      - image: mysql:latest
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
#        livenessProbe:
#          tcpSocket:
#            #host: 'mysql.demo-wordpress-mysql.svc.cluster.local'
#            port: 3306
        readinessProbe:
          exec:
            command:
              - sh
              - '-c'
              - /usr/bin/mysql -uroot -pTest1234
              - '-e'
              - show databases;
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 10
          successThreshold: 2
          failureThreshold: 10
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: pvc-mysql
