apiVersion: v1
data:
  .dockerconfigjson: # cat /.docker-config.json | base64 -w 0
kind: Secret
metadata:
  name: image-pull-secret-docker-hub
  namespace: demo-wordpress-mysql
type: kubernetes.io/dockerconfigjson